project:
  type: website

website:
  title: "분석가를 위한 인과추론 개념 정리"
  description: "현업 데이터 분석가가 인과추론을 공부하고 현업에 적용하면서 느낀 생각을 정리한 자료입니다."
  search: true
  navbar:
    left:
      - dictionary/glossary.qmd
      - contribution.qmd
    right:
      - icon: github
        href: https://github.com/CausalInferenceLab/Causal-Inference-Study-for-Analyst
  favicon: images/pseudo_lab_eng.png
  open-graph: 
    title: "분석가를 위한 인과추론 개념 정리"
    description: "현업 데이터 분석가가 인과추론을 공부하고 현업에 적용하면서 느낀 생각을 정리한 자료입니다."
    image: images/pseudo_lab_eng.png
  twitter-card: 
    title: "분석가를 위한 인과추론 개념 정리"
    description: "현업 데이터 분석가가 인과추론을 공부하고 현업에 적용하면서 느낀 생각을 정리한 자료입니다."
    image: images/pseudo_lab_eng.png



  # sidebar:
  #   style: "docked"
  #   search: true
  #   contents:
  #     # - index.qmd
  #     # - dictionary/glossary.qmd
  #     - section: "사전 사용법"
  #       contents:
  #         - term_page_intro.qmd
  #         - markdown.qmd
  #         - pr.qmd
  #     - contribution.qmd

  # google-analytics: "G-TFCJQ03RNB"
  page-footer:
    center: "by PseudoLab Causal Inference Team"
  repo-url: https://github.com/CausalInferenceLab/Causal-Inference-Study-for-Analyst
  site-url: 'https://causalinferencelab.github.io/Causal-Inference-Study-for-Analyst/'
  site-path: '/'

format:
  html:
    toc: true
    theme: cosmo
    code-copy: true



