project:
  type: website

website:
  title: "딥러닝 용어사전"
  description: "딥러닝 영어문서를 한국어로 번역하는 과정에서 용어를 통일하여 사용하기 위한 오픈소스 용어 사전입니다."
  search: true
  navbar:
    left:
      - dictionary/glossary.qmd
      - guide.qmd
      - contribution.qmd
    right:
      - icon: github
        href: https://github.com/Pseudo-Lab/deep-learning-glossary
  favicon: images/pseudo-lab-pavicon.png
  open-graph: 
    title: "딥러닝 용어사전"
    description: "딥러닝 영어문서를 한국어로 번역하는 과정에서 용어를 통일하여 사용하기 위한 오픈소스 용어 사전입니다."
    image: images/pseudo-lab-1200x630.png
  twitter-card: 
    title: "딥러닝 용어사전"
    description: "딥러닝 영어문서를 한국어로 번역하는 과정에서 용어를 통일하여 사용하기 위한 오픈소스 용어 사전입니다."
    image: images/pseudo-lab-1200x630.png



  # sidebar:
  #   style: "docked"
  #   search: true
  #   contents:
  #     # - index.qmd
  #     # - dictionary/glossary.qmd
  #     - section: "사전 사용법"
  #       contents:
  #         - term_page_intro.qmd
  #         - markdown.qmd
  #         - pr.qmd
  #     - contribution.qmd

  google-analytics: "G-TFCJQ03RNB"
  page-footer:
    center: "by HuggingFace KREW"
  repo-url: https://github.com/Pseudo-Lab/deep-learning-glossary
  site-url: 'https://pseudo-lab.github.io/deep-learning-glossary/'
  site-path: '/'

format:
  html:
    toc: true
    theme: cosmo
    code-copy: true



